---
title: "ggplot2 extensions: ggiraph"
---

### ggiraph
<http://davidgohel.github.io/ggiraph/introduction.html>

The ggiraph package let R users to make ggplot interactive. The package is an htmlwidget.

```{r, include=FALSE}
# Example from http://davidgohel.github.io/ggiraph/introduction.html
dataset <- mtcars
```

```{r message=FALSE,warning=FALSE}
library(ggplot2)
library(rvg)
library(ggiraph)

mytheme_main <- theme( panel.background = element_blank(), 
  panel.grid.major = element_line(colour = "#dddddd"), 
  axis.ticks = element_line(colour = "#dddddd") )

mytheme_map <- theme(
  panel.background = element_blank(), axis.title.x = element_blank(),
  axis.text = element_blank(), axis.line.x = element_blank(),
  axis.line.y = element_blank(), axis.title.y = element_blank(),
  axis.ticks.x = element_blank(), axis.ticks.y = element_blank() )

dataset$tooltip <- row.names(dataset)

# geom_point_interactive example
gg_point_1 <- ggplot(dataset, aes(x = disp, y = qsec, 
        color = wt, tooltip = tooltip ) ) + 
    geom_point_interactive(size=3)

# htmlwidget call
ggiraph(code = {print(gg_point_1 + mytheme_main)}, width = 7, height = 6)
```
